# Generated by Django 5.2.4 on 2025-07-28 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('residence', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.CharField(blank=True, max_length=150, null=True)),
                ('procedure', models.CharField(blank=True, max_length=150, null=True)),
                ('room', models.CharField(blank=True, max_length=150, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divine_dental_clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Hp_CO', models.CharField(blank=True, max_length=1500, null=True)),
                ('PM_Hx', models.CharField(blank=True, max_length=1500, null=True)),
                ('PD_Hx', models.CharField(blank=True, max_length=1500, null=True)),
                ('Soft_Tissue', models.CharField(blank=True, max_length=1500, null=True)),
                ('Hard_Tissue_General', models.CharField(blank=True, max_length=1500, null=True)),
                ('Hard_Tissue_Decayed', models.CharField(blank=True, max_length=1500, null=True)),
                ('Hard_Tissue_Filled', models.CharField(blank=True, max_length=1500, null=True)),
                ('Hard_Tissue_Missing', models.CharField(blank=True, max_length=1500, null=True)),
                ('Hard_Tissue_Other', models.CharField(blank=True, max_length=1500, null=True)),
                ('Investigations', models.CharField(blank=True, max_length=1500, null=True)),
                ('Occlusal_Exam', models.CharField(blank=True, max_length=1500, null=True)),
                ('Findings', models.CharField(blank=True, max_length=1500, null=True)),
                ('Plan', models.CharField(blank=True, max_length=1500, null=True)),
                ('Rx_Done', models.CharField(blank=True, max_length=1500, null=True)),
                ('TCA', models.CharField(blank=True, max_length=1500, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divine_dental_clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('doctor', models.CharField(blank=True, max_length=150, null=True)),
                ('procedure', models.CharField(blank=True, max_length=150, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divine_dental_clinic.patient')),
            ],
        ),
    ]
