# Generated by Django 5.2.4 on 2025-07-29 03:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divine_dental_clinic', '0002_leave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave',
            new_name='LeaveApplication',
        ),
    ]
