# Generated by Django 5.2.4 on 2025-07-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divine_dental_clinic', '0003_rename_leave_leaveapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
