# Generated by Django 5.2.4 on 2025-07-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divine_dental_clinic', '0005_patient_date_of_birth_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_condition', models.CharField(blank=True, max_length=1500, null=True)),
                ('drugs', models.CharField(blank=True, max_length=1500, null=True)),
                ('allergies', models.CharField(blank=True, max_length=1500, null=True)),
                ('pregnancy', models.CharField(blank=True, max_length=1500, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='divine_dental_clinic.patient')),
            ],
        ),
    ]
