# Generated by Django 5.2.4 on 2025-07-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divine_dental_clinic', '0006_medicalcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.CharField(blank=True, max_length=1500, null=True)),
                ('diastolic', models.CharField(blank=True, max_length=1500, null=True)),
                ('weight', models.CharField(blank=True, max_length=1500, null=True)),
                ('height', models.CharField(blank=True, max_length=1500, null=True)),
                ('hip', models.CharField(blank=True, max_length=1500, null=True)),
                ('waist', models.CharField(blank=True, max_length=1500, null=True)),
                ('temp', models.CharField(blank=True, max_length=1500, null=True)),
                ('pulse', models.CharField(blank=True, max_length=1500, null=True)),
                ('respiration', models.CharField(blank=True, max_length=1500, null=True)),
                ('oxygen_saturation', models.CharField(blank=True, max_length=1500, null=True)),
                ('pain', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='divine_dental_clinic.patient')),
            ],
        ),
    ]
