# Generated by Django 5.2.4 on 2025-07-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divine_dental_clinic', '0008_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
