# Generated by Django 5.2.4 on 2025-07-30 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divine_dental_clinic', '0014_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1', models.CharField(blank=True, max_length=150, null=True)),
                ('service2', models.CharField(blank=True, max_length=150, null=True)),
                ('service3', models.CharField(blank=True, max_length=150, null=True)),
                ('unit1', models.CharField(blank=True, max_length=150, null=True)),
                ('unit2', models.CharField(blank=True, max_length=150, null=True)),
                ('unit3', models.CharField(blank=True, max_length=150, null=True)),
                ('cost1', models.CharField(blank=True, max_length=150, null=True)),
                ('cost2', models.CharField(blank=True, max_length=150, null=True)),
                ('cost3', models.CharField(blank=True, max_length=150, null=True)),
                ('waiver_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('waiver', models.CharField(blank=True, max_length=150, null=True)),
                ('lab', models.CharField(blank=True, max_length=150, null=True)),
                ('deduct', models.CharField(blank=True, max_length=150, null=True)),
                ('total', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divine_dental_clinic.patient')),
            ],
        ),
    ]
